# Python Exercise

## Basic Exerices

#### 1) Make a function that takes two values and multiply them together

In [ ]:
import functools

In [ ]:
def multfn(val_1, val_2):
  return val_1 * val_2

In [ ]:
a = 5
b = 10
c = multfn(a, b)
print(c)

50


#### 2) Do the same using a class
####       * At initialisation store the two values as attributes
####       * method does the multiplication

In [ ]:
class MultCl:
  def __init__(self, val_1, val_2):
    self.val_1 = val_1
    self.val_2 = val_2
  ## 2)
  def mult(self):
    return multfn(self.val_1, self.val_2)
  ## 3)
  def mult_list(self):
    return list(map(lambda x,y: multfn(x,y), self.val_1, self.val_2))
  ## 4)
  def mult_vec(self):
    return functools.reduce(lambda x,y: x+y, self.mult_list())

In [ ]:
mcl = MultCl(a, b)
print(mcl.mult())

50


#### 3) Make two lists of same size containing the values and try the multiplication, if fails make a method to multiply a list (elementwise)

In [ ]:
c = [1, 2, 3, 4]
d = [5, 6, 7, 8]

# print(multfn(c, d))
mcl_list = MultCl(c, d)
print(mcl_list.mult_list())

[5, 12, 21, 32]


#### 4) Considering the two lists as vectors of 1xN and Nx1, make a method to do the vector multiplication; The result must be a scalar

In [ ]:
print(mcl_list.mult_vec())

70


#### 5) Make a function to take a list of lists and store them in a dictionary; the dictionary keys must be the row indexes. Get the matrix elements by index and print

In [ ]:
init_list = [1, 2, 3, 4, 5]
mat_list =  [init_list,
            list(map(lambda x: 2*x, init_list)),
            list(map(lambda x: 3*x, init_list)),
             list(map(lambda x: 5*x, init_list)),]

print(mat_list)

def list_to_mat(mat_list):
  mat = dict()
  for i in range(3):
    mat[i] = mat_list[i]
  
  return mat

mat = list_to_mat(mat_list)
for i in range(3):
  for j in range(5):
    print(mat[i][j])
  print("")

[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [5, 10, 15, 20, 25]]
1
2
3
4
5

2
4
6
8
10

3
6
9
12
15



#### 6) Class inheritance;
#### * Take the class that does Multiplication as the parent class
#### * Make a child class and inherit the methods and attributes from the parent class
#### * Child class stores a scalar value
#### * Use the scala value to scale an output from one of the methods in the parent class

In [ ]:
class Scale(MultCl):
  def __init__(self, scale, val_1, val_2):
    super().__init__(val_1, val_2)
    self.scale = scale

  def scale_scalar(self):
    ## print(super.mult())
    return self.scale * super().mult()

  def scale_list(self):
    return list(map(lambda x: self.scale * x, super().mult_list()))

In [ ]:
scaler_scalar = Scale(2, 5, 3)
print(scaler_scalar.scale_scalar())

scaler_list = Scale(3, [1, 2, 3], [4, 5, 6])
print(scaler_list.scale_list())

30
[12, 30, 54]


## Numpy Exercises 
#### (check the numpy manual if necessary)

#### 7) Make a matrix out of the list of lists using numpy method 

In [ ]:
import numpy as np

np_mat = np.array(mat_list)
print(np_mat)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]]


#### 8) Transpose the matrix

In [ ]:
np_mat_t = np_mat.T
print(np_mat_t)

[[ 1  2  3  5]
 [ 2  4  6 10]
 [ 3  6  9 15]
 [ 4  8 12 20]
 [ 5 10 15 25]]


#### 9) Take the dot product between the matrix and its transpose

In [ ]:
np_dot = np_mat.dot(np_mat_t)
print(np_dot)

[[  55  110  165  275]
 [ 110  220  330  550]
 [ 165  330  495  825]
 [ 275  550  825 1375]]


#### 10) Reshape the matrix to a new shape

In [ ]:
np_reshaped = np_dot.reshape((2, 8))
print(np_reshaped)

[[  55  110  165  275  110  220  330  550]
 [ 165  330  495  825  275  550  825 1375]]


#### 11) Make a 3D tensor containing random numbers

In [ ]:
np_rand_tensor = np.random.normal(size=[3, 5, 7])
print(np_rand_tensor)

[[[-0.08995885  0.79335016  0.49112908  0.19281932  0.95571721
   -0.98609372  0.63649018]
  [ 0.52433554 -0.77394452  1.93517018  0.01979926  0.50552411
   -1.70529892  0.75352167]
  [-1.85953546 -0.01316086  0.90801311 -0.95149062  1.20013759
   -0.70581032  0.00220539]
  [-0.75672501  1.5595299  -2.18599791  0.37864377 -0.98708234
    1.01964531 -1.81613127]
  [-0.87713845  1.056784   -0.67309513  0.93776049 -0.99623592
   -0.94807887  1.02577528]]

 [[ 0.20621765  0.86441394 -1.69367734 -0.07740664  0.08733073
   -0.12862427  0.1164863 ]
  [ 0.2688248  -0.12485216 -0.25851073  0.66893937 -0.67046937
    0.46762597 -0.27222154]
  [-0.12951034 -0.78842854 -1.05518471 -0.9175537   0.30529337
   -0.74284415 -1.27946389]
  [ 0.08560616  1.43644369 -0.6741566   0.17252613  0.37581264
    0.62097859 -0.75599882]
  [ 0.75414166 -2.07621285 -0.33804145 -0.92496869 -1.54273117
   -0.36327739 -0.68331933]]

 [[-0.15259292  0.4391274  -0.6640591   0.08384268  0.28824154
   -0.3499266  -1.50756